package com.brutiful.netprobe.model

object PortData {
    val initialPorts = listOf(
        PortInfo(7, "Echo", "Echo Protocol - Used for testing and measurement of network connectivity."),
        PortInfo(9, "Discard", "Discard Protocol - Discards all data sent to it; used for debugging."),
        PortInfo(13, "Daytime", "Daytime Protocol - Returns the current date and time as a string."),
        PortInfo(17, "QOTD", "Quote of the Day - Returns a short message or quote."),
        PortInfo(19, "Chargen", "Character Generator - Sends a continuous stream of characters."),
        PortInfo(20, "FTP-Data", "File Transfer Protocol (Data) - Used for actual file data transfer."),
        PortInfo(21, "FTP", "File Transfer Protocol (Control) - Used for sending commands and receiving responses."),
        PortInfo(22, "SSH", "Secure Shell - Provides secure remote login and command execution."),
        PortInfo(23, "Telnet", "Insecure Remote Login - Provides unencrypted terminal emulation."),
        PortInfo(25, "SMTP", "Simple Mail Transfer Protocol - Primary protocol for sending email."),
        PortInfo(37, "Time", "Time Protocol - Returns the current time as a 32-bit integer."),
        PortInfo(42, "Nameserver", "Host Name Server - Early protocol for mapping names to addresses."),
        PortInfo(43, "WHOIS", "WHOIS Protocol - Queries databases for domain registration and IP ownership."),
        PortInfo(49, "TACACS", "Terminal Access Controller Access-Control System - Used for authentication."),
        PortInfo(53, "DNS", "Domain Name System - Resolves hostnames to IP addresses."),
        PortInfo(67, "DHCP-Server", "DHCP Server Port - Used for assigning IP addresses to clients."),
        PortInfo(68, "DHCP-Client", "DHCP Client Port - Used by clients to request IP addresses."),
        PortInfo(69, "TFTP", "Trivial File Transfer Protocol - Simple, diskless boot protocol."),
        PortInfo(70, "Gopher", "Gopher Protocol - Early document search and retrieval system."),
        PortInfo(79, "Finger", "Finger Protocol - Provides information about users on a system."),
        PortInfo(80, "HTTP", "Hypertext Transfer Protocol - The foundation of the World Wide Web."),
        PortInfo(88, "Kerberos", "Kerberos Network Authentication - Provides secure authentication."),
        PortInfo(102, "ISO-TSAP", "ISO Transport Service Access Point - Used for OSI network protocols."),
        PortInfo(109, "POP2", "Post Office Protocol v2 - Older protocol for email retrieval."),
        PortInfo(110, "POP3", "Post Office Protocol v3 - Modern protocol for email retrieval."),
        PortInfo(111, "RPCBIND", "Remote Procedure Call Bind - Maps RPC services to port numbers."),
        PortInfo(113, "Ident", "Identification Protocol - Returns the identity of a user on a TCP connection."),
        PortInfo(115, "SFTP", "Simple File Transfer Protocol - An older, simpler alternative to FTP."),
        PortInfo(118, "SQL-Services", "SQL Services - Used for early SQL database communication."),
        PortInfo(119, "NNTP", "Network News Transfer Protocol - Used for USENET news articles."),
        PortInfo(123, "NTP", "Network Time Protocol - Synchronizes device clocks across a network."),
        PortInfo(135, "RPC-EPMAP", "RPC Endpoint Mapper - Used for locating RPC services in Windows."),
        PortInfo(137, "NetBIOS-NS", "NetBIOS Name Service - Used for name resolution in older Windows networks."),
        PortInfo(138, "NetBIOS-DGM", "NetBIOS Datagram Service - Used for connectionless messaging in Windows."),
        PortInfo(139, "NetBIOS-SSN", "NetBIOS Session Service - Used for file and printer sharing in older Windows."),
        PortInfo(143, "IMAP", "Internet Message Access Protocol - Advanced protocol for email retrieval."),
        PortInfo(161, "SNMP", "Simple Network Management Protocol - Used for monitoring and managing devices."),
        PortInfo(162, "SNMP-Trap", "SNMP Trap - Used by devices to send asynchronous notifications."),
        PortInfo(179, "BGP", "Border Gateway Protocol - Routing protocol for the internet."),
        PortInfo(194, "IRC", "Internet Relay Chat - Early protocol for text-based chat."),
        PortInfo(201, "AppleTalk", "AppleTalk Routing Maintenance - Apple's legacy networking protocol."),
        PortInfo(389, "LDAP", "Lightweight Directory Access Protocol - Used for accessing directory services."),
        PortInfo(443, "HTTPS", "Hypertext Transfer Protocol Secure - Encrypted web traffic."),
        PortInfo(445, "SMB", "Microsoft-DS (SMB) - Modern Windows file and printer sharing."),
        PortInfo(464, "Kerberos-PW", "Kerberos Change/Set Password - Used for managing Kerberos credentials."),
        PortInfo(465, "SMTPS", "SMTP over SSL/TLS - Securely sending email."),
        PortInfo(500, "ISAKMP", "IKE/ISAKMP - Used for establishing IPsec VPN connections."),
        PortInfo(512, "Rexec", "Remote Execution - Execute commands on a remote system (insecure)."),
        PortInfo(513, "Rlogin", "Remote Login - Terminal access to remote systems (insecure)."),
        PortInfo(514, "Syslog", "System Log - Protocol for sending log messages to a central server."),
        PortInfo(515, "LPD", "Line Printer Daemon - Protocol for network printing."),
        PortInfo(520, "RIP", "Routing Information Protocol - Early distance-vector routing protocol."),
        PortInfo(530, "RPC", "Remote Procedure Call - Used for executing code on other systems."),
        PortInfo(543, "Klogin", "Kerberos Login - Secure remote login via Kerberos."),
        PortInfo(544, "Kshell", "Kerberos Shell - Secure remote command execution via Kerberos."),
        PortInfo(548, "AFP", "Apple Filing Protocol - Apple's proprietary file sharing protocol."),
        PortInfo(554, "RTSP", "Real Time Streaming Protocol - Controls media streaming (IP Cameras)."),
        PortInfo(587, "SMTP-Submission", "SMTP Submission - Modern port for sending email from clients."),
        PortInfo(593, "RPC-over-HTTP", "Microsoft RPC over HTTP - Encapsulates RPC in HTTP requests."),
        PortInfo(631, "IPP", "Internet Printing Protocol - Modern protocol for network printing."),
        PortInfo(636, "LDAPS", "LDAP over SSL/TLS - Secure access to directory services."),
        PortInfo(873, "Rsync", "Rsync Protocol - Efficiently synchronizes files between systems."),
        PortInfo(902, "VMware", "VMware Server - Used for managing VMware virtual machines."),
        PortInfo(989, "FTPS-Data", "FTP over SSL/TLS (Data) - Secure file transfer data port."),
        PortInfo(990, "FTPS-Control", "FTP over SSL/TLS (Control) - Secure FTP command port."),
        PortInfo(992, "TelnetS", "Telnet over TLS - Secure terminal access."),
        PortInfo(993, "IMAPS", "IMAP over SSL/TLS - Secure email retrieval."),
        PortInfo(995, "POP3S", "POP3 over SSL/TLS - Secure email retrieval."),
        PortInfo(1025, "NFS/IIS", "Commonly used for Microsoft IIS or NFS dynamic ports."),
        PortInfo(1433, "MSSQL", "Microsoft SQL Server - Relational database management system."),
        PortInfo(1434, "MSSQL-Monitor", "Microsoft SQL Server Monitor - Used for monitoring SQL Server."),
        PortInfo(1521, "Oracle", "Oracle Database - Relational database management system."),
        PortInfo(1701, "L2TP", "Layer 2 Tunneling Protocol - Used for VPN connections."),
        PortInfo(1723, "PPTP", "Point-to-Point Tunneling Protocol - Older VPN protocol."),
        PortInfo(1812, "RADIUS-Auth", "RADIUS Authentication - Used for network access control."),
        PortInfo(1813, "RADIUS-Acct", "RADIUS Accounting - Tracks user network usage."),
        PortInfo(2049, "NFS", "Network File System - Protocol for sharing files between Unix systems."),
        PortInfo(2375, "Docker", "Docker REST API - Used for managing Docker containers (unencrypted)."),
        PortInfo(2376, "Docker-TLS", "Docker REST API Secure - Encrypted Docker management."),
        PortInfo(3306, "MySQL", "MySQL Database - Popular open-source database system."),
        PortInfo(3389, "RDP", "Remote Desktop Protocol - Graphical remote access to Windows."),
        PortInfo(3690, "Subversion", "SVN (Subversion) - Version control system protocol."),
        PortInfo(4444, "Metasploit", "Metasploit Default Port - Often used for reverse shells and exploits."),
        PortInfo(5000, "UPnP/NAS", "UPnP or NAS Management - Often used by Synology or generic IoT devices."),
        PortInfo(5060, "SIP", "Session Initiation Protocol - VoIP signaling port."),
        PortInfo(5061, "SIPS", "SIP over TLS - Secure VoIP signaling."),
        PortInfo(5432, "PostgreSQL", "PostgreSQL Database - Advanced open-source database system."),
        PortInfo(5555, "ADB", "Android Debug Bridge - Used for debugging Android devices over network."),
        PortInfo(5631, "pcAnywhere", "Symantec pcAnywhere - Remote access software."),
        PortInfo(5900, "VNC", "Virtual Network Computing - Graphical remote access protocol."),
        PortInfo(5984, "CouchDB", "CouchDB - NoSQL database system."),
        PortInfo(6379, "Redis", "Redis - High-speed in-memory data structure store."),
        PortInfo(6667, "IRC-Alt", "IRC Alternative Port - Common port for text-based chat."),
        PortInfo(8000, "Web-Alt", "Common Web Alternative - Often used for development servers."),
        PortInfo(8008, "Chromecast", "Google Chromecast - Used for media casting and discovery."),
        PortInfo(8080, "HTTP-Proxy", "HTTP Proxy / Alternative - Common port for web proxies and caches."),
        PortInfo(8096, "Jellyfin", "Jellyfin Media Server - Open-source media streaming platform."),
        PortInfo(8123, "Home-Assistant", "Home Assistant - Smart home automation hub."),
        PortInfo(8443, "HTTPS-Alt", "HTTPS Alternative - Common port for secure management interfaces."),
        PortInfo(8888, "Jupyter/Alt", "Jupyter Notebook or HTTP Alternative - Often used for dev tools."),
        PortInfo(9000, "Portainer/Alt", "Portainer or SonarQube - Used for dashboard management."),
        PortInfo(9100, "JetDirect", "HP JetDirect - Standard port for raw network printing."),
        PortInfo(9200, "Elasticsearch", "Elasticsearch - Distributed search and analytics engine."),
        PortInfo(9443, "HTTPS-Alt", "HTTPS Alternative - Often used for secure web consoles."),
        PortInfo(10000, "Webmin", "Webmin - Web-based interface for system administration."),
        PortInfo(10001, "Ubiquiti", "Ubiquiti Discovery - Used for finding Ubiquiti network devices."),
        PortInfo(27017, "MongoDB", "MongoDB Database - Popular NoSQL database system."),
        PortInfo(32400, "Plex", "Plex Media Server - Home media streaming and organization.")
    )
}
